dataSource:
  host: localhost
  port: 5432
  dbName: silo_dev
  user: root
  password: root
restServer:
  applicationPath: /sts/v1
  port: 8000
serial:
  rtuPorts:
    - COM8
  relay:
    port: COM11
    powerRelay:
      address: 0x01
      channel: 0
  delay:
    sensorChargeDelayAsMillisecond: 1500
    additionalDelayAfterMeasurementAsSecond: 40
    delayAfterRTURelayOpenAsSecond: 10
    delayAfterSyncMessageResponseAsMillisecond: 2000
