dataSource:
  host: localhost
  port: 5432
  dbName: silo_dev
  user: root
  password: root
restServer:
  applicationPath: /sts/v1
  port: 8000
serial:
  rtuPorts:
    - COM7
  relay:
    port: COM5
    powerRelay:
      address: 0xFE
      channel: 0
    controlRelayAddresses:
  delay:
    sensorChargeDelayAsMillisecond: 1500
    additionalDelayAfterMeasurementAsSecond: 40
    delayAfterRTURelayOpenAsSecond: 10
    delayAfterSyncMessageResponseAsMillisecond: 2000
    delayApplicationLoadingAsSeconds: 15
fake: false
